/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.sand.accsys.infrastructure.idl.thrift.struct;

import org.apache.thrift.TException;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;
import org.apache.thrift.scheme.TupleScheme;

import javax.annotation.Generated;
import java.util.*;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked"})
@Generated(value = "Autogenerated by Thrift Compiler (0.9.3)", date = "2016-03-21")
public class FileMate implements org.apache.thrift.TBase<FileMate, FileMate._Fields>, java.io.Serializable, Cloneable, Comparable<FileMate> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("FileMate");

  private static final org.apache.thrift.protocol.TField FILE_NAME_FIELD_DESC = new org.apache.thrift.protocol.TField("fileName", org.apache.thrift.protocol.TType.STRING, (short)1);
  private static final org.apache.thrift.protocol.TField FILE_UNIT_FIELD_DESC = new org.apache.thrift.protocol.TField("fileUnit", org.apache.thrift.protocol.TType.STRING, (short)2);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new FileMateStandardSchemeFactory());
    schemes.put(TupleScheme.class, new FileMateTupleSchemeFactory());
  }

  /**
   * 文件�?
   */
  public String fileName; // required
  /**
   * 文件单元
   */
  public String fileUnit; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    /**
     * 文件�?
     */
    FILE_NAME((short)1, "fileName"),
    /**
     * 文件单元
     */
    FILE_UNIT((short)2, "fileUnit");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // FILE_NAME
          return FILE_NAME;
        case 2: // FILE_UNIT
          return FILE_UNIT;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.FILE_NAME, new org.apache.thrift.meta_data.FieldMetaData("fileName", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.FILE_UNIT, new org.apache.thrift.meta_data.FieldMetaData("fileUnit", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(FileMate.class, metaDataMap);
  }

  public FileMate() {
  }

  public FileMate(
    String fileName,
    String fileUnit)
  {
    this();
    this.fileName = fileName;
    this.fileUnit = fileUnit;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public FileMate(FileMate other) {
    if (other.isSetFileName()) {
      this.fileName = other.fileName;
    }
    if (other.isSetFileUnit()) {
      this.fileUnit = other.fileUnit;
    }
  }

  public FileMate deepCopy() {
    return new FileMate(this);
  }

  @Override
  public void clear() {
    this.fileName = null;
    this.fileUnit = null;
  }

  /**
   * 文件�?
   */
  public String getFileName() {
    return this.fileName;
  }

  /**
   * 文件�?
   */
  public FileMate setFileName(String fileName) {
    this.fileName = fileName;
    return this;
  }

  public void unsetFileName() {
    this.fileName = null;
  }

  /** Returns true if field fileName is set (has been assigned a value) and false otherwise */
  public boolean isSetFileName() {
    return this.fileName != null;
  }

  public void setFileNameIsSet(boolean value) {
    if (!value) {
      this.fileName = null;
    }
  }

  /**
   * 文件单元
   */
  public String getFileUnit() {
    return this.fileUnit;
  }

  /**
   * 文件单元
   */
  public FileMate setFileUnit(String fileUnit) {
    this.fileUnit = fileUnit;
    return this;
  }

  public void unsetFileUnit() {
    this.fileUnit = null;
  }

  /** Returns true if field fileUnit is set (has been assigned a value) and false otherwise */
  public boolean isSetFileUnit() {
    return this.fileUnit != null;
  }

  public void setFileUnitIsSet(boolean value) {
    if (!value) {
      this.fileUnit = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case FILE_NAME:
      if (value == null) {
        unsetFileName();
      } else {
        setFileName((String)value);
      }
      break;

    case FILE_UNIT:
      if (value == null) {
        unsetFileUnit();
      } else {
        setFileUnit((String)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case FILE_NAME:
      return getFileName();

    case FILE_UNIT:
      return getFileUnit();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case FILE_NAME:
      return isSetFileName();
    case FILE_UNIT:
      return isSetFileUnit();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof FileMate)
      return this.equals((FileMate)that);
    return false;
  }

  public boolean equals(FileMate that) {
    if (that == null)
      return false;

    boolean this_present_fileName = true && this.isSetFileName();
    boolean that_present_fileName = true && that.isSetFileName();
    if (this_present_fileName || that_present_fileName) {
      if (!(this_present_fileName && that_present_fileName))
        return false;
      if (!this.fileName.equals(that.fileName))
        return false;
    }

    boolean this_present_fileUnit = true && this.isSetFileUnit();
    boolean that_present_fileUnit = true && that.isSetFileUnit();
    if (this_present_fileUnit || that_present_fileUnit) {
      if (!(this_present_fileUnit && that_present_fileUnit))
        return false;
      if (!this.fileUnit.equals(that.fileUnit))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    List<Object> list = new ArrayList<Object>();

    boolean present_fileName = true && (isSetFileName());
    list.add(present_fileName);
    if (present_fileName)
      list.add(fileName);

    boolean present_fileUnit = true && (isSetFileUnit());
    list.add(present_fileUnit);
    if (present_fileUnit)
      list.add(fileUnit);

    return list.hashCode();
  }

  @Override
  public int compareTo(FileMate other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetFileName()).compareTo(other.isSetFileName());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetFileName()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.fileName, other.fileName);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetFileUnit()).compareTo(other.isSetFileUnit());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetFileUnit()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.fileUnit, other.fileUnit);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("FileMate(");
    boolean first = true;

    sb.append("fileName:");
    if (this.fileName == null) {
      sb.append("null");
    } else {
      sb.append(this.fileName);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("fileUnit:");
    if (this.fileUnit == null) {
      sb.append("null");
    } else {
      sb.append(this.fileUnit);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws TException {
    // check for required fields
    if (fileName == null) {
      throw new TProtocolException("Required field 'fileName' was not present! Struct: " + toString());
    }
    if (fileUnit == null) {
      throw new TProtocolException("Required field 'fileUnit' was not present! Struct: " + toString());
    }
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class FileMateStandardSchemeFactory implements SchemeFactory {
    public FileMateStandardScheme getScheme() {
      return new FileMateStandardScheme();
    }
  }

  private static class FileMateStandardScheme extends StandardScheme<FileMate> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, FileMate struct) throws TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // FILE_NAME
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.fileName = iprot.readString();
              struct.setFileNameIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // FILE_UNIT
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.fileUnit = iprot.readString();
              struct.setFileUnitIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, FileMate struct) throws TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.fileName != null) {
        oprot.writeFieldBegin(FILE_NAME_FIELD_DESC);
        oprot.writeString(struct.fileName);
        oprot.writeFieldEnd();
      }
      if (struct.fileUnit != null) {
        oprot.writeFieldBegin(FILE_UNIT_FIELD_DESC);
        oprot.writeString(struct.fileUnit);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class FileMateTupleSchemeFactory implements SchemeFactory {
    public FileMateTupleScheme getScheme() {
      return new FileMateTupleScheme();
    }
  }

  private static class FileMateTupleScheme extends TupleScheme<FileMate> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, FileMate struct) throws TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      oprot.writeString(struct.fileName);
      oprot.writeString(struct.fileUnit);
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, FileMate struct) throws TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      struct.fileName = iprot.readString();
      struct.setFileNameIsSet(true);
      struct.fileUnit = iprot.readString();
      struct.setFileUnitIsSet(true);
    }
  }

}

